### ISSUE TITLE
Typo on MENU

### ISSUE THREAD

**Issue by cocus** [cml37/dos-utils#1]
I think this should be `MENU` and not `ENU`
https://github.com/cml37/dos-utils/blob/5a695f3a254244886df73bebebed16e819c83e59/network/pxeboot/raspberry_pi_configuration_script.txt#L44

I haven't tried it but I remember when I set these up, the actual elements were `MENU`.
Simple thing but for someone that might be running these steps blindly, this might be overlooked. 

Thanks and btw, nice YouTube videos!

**Comment by cml37** [comment]
Great catch!  Fixed.  Glad you are enjoying the videos... saw that you subscribed to the channel.  Thank you :-)
