### ISSUE TITLE
Additional notes on dos file sharing

### ISSUE THREAD

**Issue by SQLServerIO** [cml37/dos-utils#2]
I am using 86box as the server with an ne2000 nic to make things a bit easier.
I then use a boot floppy to setup any new retro hardware on the network.

I'm not sure how your two instances were able to see each other without a wins server or the like. I added mine to the hosts file and used the addname command to make it possible to use net use\view commands.
ADDNAME \\machine_name 192.168.111.1 it's pretty straight forward.

**Comment by cml37** [comment]
Makes sense!  Ya, pretty sure I have a WINS server on the network.  Alternatively, I think that machines could be accessed directly via IP address.

**Comment by SQLServerIO** [comment]
the addname allows netbios redirect via ip. You can ping all day long but you can't see the shares.
You are limited to six entries but I only need one on each client for all of them to see the server.
I thought it was a DNS issue at first that's why I added the computers to the hosts file. That didn't fix it addname did.

Maybe more testing is in order.
